In [13]:
# Data
import numpy as np
import pandas as pd

# Visualization
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go

#warning
import warnings
warnings.filterwarnings('ignore')

In [14]:
# 읽어올 엑셀 파일 지정
filename = './dataset/생산지수data.xlsx'

# 엑셀 파일 읽어 오기
df = pd.read_excel(filename, engine='openpyxl')

In [15]:
df

,시점,산업생산지수(원지수),생산자제품 출하지수(원지수),생산자제품 재고지수(원지수),내수출하지수(원지수),수출출하지수(원지수),산업생산지수(계절조정),생산자제품 출하지수(계절조정),생산자제품 재고지수(계절조정),내수출하지수(계절조정),수출출하지수(계절조정)
0,2005.01 월,78.607,78.515,71.464,80.652,74.656,77.921,79.152,69.683,80.534,76.730
1,2005.02 월,67.195,68.774,70.343,69.990,66.587,75.991,76.797,69.459,78.674,73.584
2,2005.03 월,82.309,83.190,70.055,85.292,79.254,77.590,78.208,69.212,80.134,75.005
3,2005.04 월,79.399,80.019,70.623,81.956,76.616,76.824,77.426,70.340,78.998,74.709
4,2005.05 월,79.313,79.148,71.815,81.630,74.732,76.642,76.797,71.577,78.998,73.060
...,...,...,...,...,...,...,...,...,...,...,...
208,2022.05 월,102.900,99.900,123.800,102.700,95.000,100.000,98.100,122.900,100.700,93.600
209,2022.06 월,101.500,96.000,128.300,101.300,86.500,102.400,97.100,129.200,103.000,86.600
210,2022.07 월,101.600,99.300,128.600,101.300,95.700,101.600,100.600,127.700,103.500,95.500
211,2022.08 월,97.000,95.600,128.400,99.200,89.200,102.700,101.500,126.700,105.300,94.600
212,2022.09 월,97.000,95.000,126.800,97.600,90.500,101.300,99.700,126.500,103.400,93.100

In [16]:
df = df.drop(df.columns[[0]], axis=1)

In [17]:
df2 = df

In [18]:
df = df.corr()
df = df.apply(lambda x: round(x ,2))
df

,산업생산지수(원지수),생산자제품 출하지수(원지수),생산자제품 재고지수(원지수),내수출하지수(원지수),수출출하지수(원지수),산업생산지수(계절조정),생산자제품 출하지수(계절조정),생산자제품 재고지수(계절조정),내수출하지수(계절조정),수출출하지수(계절조정)
산업생산지수(원지수),1.00,0.99,0.56,0.96,0.86,0.87,0.88,0.57,0.83,0.75
생산자제품 출하지수(원지수),0.99,1.00,0.49,0.95,0.89,0.86,0.87,0.50,0.81,0.78
생산자제품 재고지수(원지수),0.56,0.49,1.00,0.63,0.19,0.66,0.61,1.00,0.77,0.23
내수출하지수(원지수),0.96,0.95,0.63,1.00,0.71,0.82,0.82,0.64,0.86,0.59
수출출하지수(원지수),0.86,0.89,0.19,0.71,1.00,0.76,0.79,0.20,0.58,0.93
산업생산지수(계절조정),0.87,0.86,0.66,0.82,0.76,1.00,0.99,0.66,0.95,0.83
생산자제품 출하지수(계절조정),0.88,0.87,0.61,0.82,0.79,0.99,1.00,0.61,0.94,0.87
생산자제품 재고지수(계절조정),0.57,0.50,1.00,0.64,0.20,0.66,0.61,1.00,0.77,0.23
내수출하지수(계절조정),0.83,0.81,0.77,0.86,0.58,0.95,0.94,0.77,1.00,0.65
수출출하지수(계절조정),0.75,0.78,0.23,0.59,0.93,0.83,0.87,0.23,0.65,1.00

In [19]:
from scipy import signal
def ccf_values(series1, series2):
    p = series1
    q = series2
    p = (p - np.mean(p)) / (np.std(p) * len(p))
    q = (q - np.mean(q)) / (np.std(q))  
    c = np.correlate(p, q, 'full')
    return c

In [20]:
ccf_ielts1 = ccf_values(df['산업생산지수(원지수)'], df['생산자제품 재고지수(원지수)'])
a = np.max(ccf_ielts1)
a

0.8069917272538873

In [21]:
ccf_ielts2 = ccf_values(df['산업생산지수(원지수)'], df['생산자제품 재고지수(계절조정)'])
a = np.max(ccf_ielts2)
a

0.8105088872495454

In [22]:
ccf_ielts3 = ccf_values(df['생산자제품 재고지수(원지수)'], df['내수출하지수(원지수)'])
a = np.max(ccf_ielts3)
a

0.5978716835649366

In [23]:
ccf_ielts4 = ccf_values(df['생산자제품 출하지수(계절조정)'], df['내수출하지수(원지수)'])
a = np.max(ccf_ielts4)
a

0.5722206373879288

In [24]:
ccf_ielts5 = ccf_values(df['생산자제품 재고지수(계절조정)'], df['산업생산지수(계절조정)'])
a = np.max(ccf_ielts5)
a

0.8125692202386989